# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-07-15 15:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('threadcard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('subscribe', models.BooleanField(default=False)),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reader', to=settings.AUTH_USER_MODEL)),
                ('writter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Subscribe',
            },
        ),
    ]
