# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-07-15 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threadcard', '0002_subscribe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscribe',
            unique_together=set([('writter', 'reader')]),
        ),
    ]
