# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-08-05 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threadcard', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
