# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-08-09 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threadcard', '0005_feedback_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcover',
            name='id',
            field=models.SlugField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
