# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-08-18 17:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('threadcard', '0007_auto_20180809_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userintreset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('bookname', models.CharField(blank=True, max_length=64, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('weburl', models.URLField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=128)),
                ('publisher', models.CharField(blank=True, max_length=128)),
                ('tagline', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('toberead', models.BooleanField(default=True)),
                ('read', models.BooleanField(default=False)),
                ('reading', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Userintreset',
            },
        ),
        migrations.AddField(
            model_name='thread',
            name='author',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='thread',
            name='publisher',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
