# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-11-10 11:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import threadcard.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('threadcard', '0008_auto_20180818_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.SlugField(default=threadcard.models.get_podcast_short_code, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('embed', models.CharField(blank=True, max_length=512)),
                ('likes', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Podcast',
            },
        ),
        migrations.CreateModel(
            name='Podcastbooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('bookname', models.CharField(blank=True, max_length=64, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('weburl', models.URLField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=128)),
                ('publisher', models.CharField(blank=True, max_length=128)),
                ('tagline', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threadcard.Podcast')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Podcastbooks',
            },
        ),
    ]
