# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-12-21 12:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('threadcard', '0009_podcast_podcastbooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('message', models.CharField(max_length=500)),
                ('live', models.BooleanField(default=True)),
                ('subcomment_count', models.IntegerField(default=0)),
                ('image', models.FileField(blank=True, null=True, upload_to='podcast_threads')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threadcard.Podcast')),
            ],
            options={
                'db_table': 'PodcastThread',
            },
        ),
    ]
