# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-12-21 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threadcard', '0010_podcastthread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastthread',
            name='subcomment_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
