# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-01-10 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threadcard', '0011_auto_20181221_1216'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='podcast',
            unique_together=set([('created_by', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='podcastbooks',
            unique_together=set([('user', 'podcast', 'bookname')]),
        ),
        migrations.AlterUniqueTogether(
            name='userintreset',
            unique_together=set([('user', 'bookname', 'author')]),
        ),
    ]
