# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-01-12 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threadcard', '0012_auto_20190110_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcover',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='podcastbooks',
            name='bookname',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='podcastthread',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
